{"name": "test_loginError[udata0]", "status": "passed", "parameters": [{"name": "udata", "value": "{'longtransportid': 1093, 'username': 'syx9220', 'password': 123456}"}], "start": 1660207750891, "stop": 1660207751395, "uuid": "0e2beb68-e227-4ecc-8ac7-fcec0a3b879f", "historyId": "47ea4e34bbf082a7c68fcbe9a27e34b2", "testCaseId": "d71a2910c5a241c986cecb1081c4532c", "fullName": "py_test.TestCase#test_loginError", "labels": [{"name": "suite", "value": "py_test"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "xiaocaodeMac.local"}, {"name": "thread", "value": "798-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "py_test"}]}