{"name": "test_loginError[udata0]", "status": "passed", "parameters": [{"name": "udata", "value": "{'longtransportid': 1093, 'username': 'syx9220', 'password': 123456}"}], "start": 1660267456175, "stop": 1660267456513, "uuid": "99de5cf5-b302-4596-8b09-bb05ca6fb273", "historyId": "47ea4e34bbf082a7c68fcbe9a27e34b2", "testCaseId": "d71a2910c5a241c986cecb1081c4532c", "fullName": "py_test.TestCase#test_loginError", "labels": [{"name": "suite", "value": "py_test"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "xiaocaodeMac.local"}, {"name": "thread", "value": "1363-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "py_test"}]}