{"name": "test_loginError[udata2]", "status": "passed", "parameters": [{"name": "udata", "value": "{'longtransportid': 1093, 'username': 'syx922', 'password': 123457}"}], "start": 1660548036361, "stop": 1660548036782, "uuid": "785cef94-ec82-41d1-834b-a938d2f99072", "historyId": "5968b7d198c9f57a539543ad9031a9c1", "testCaseId": "d71a2910c5a241c986cecb1081c4532c", "fullName": "py_test.TestCase#test_loginError", "labels": [{"name": "suite", "value": "py_test"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "xiaocaodeMac.local"}, {"name": "thread", "value": "31236-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "py_test"}]}