{"name": "test_loginError[udata2]", "status": "passed", "parameters": [{"name": "udata", "value": "{'longtransportid': 1093, 'username': 'syx922', 'password': 123457}"}], "start": 1660213675513, "stop": 1660213675898, "uuid": "6f03e37e-586e-48ef-8504-6d63f177c85a", "historyId": "5968b7d198c9f57a539543ad9031a9c1", "testCaseId": "d71a2910c5a241c986cecb1081c4532c", "fullName": "py_test.TestCase#test_loginError", "labels": [{"name": "tag", "value": "@pytest.mark.filterwarnings('ignore:api v1')"}, {"name": "suite", "value": "py_test"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "xiaocaodeMac.local"}, {"name": "thread", "value": "5339-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "py_test"}]}