{"name": "test_loginError[udata0]", "status": "passed", "parameters": [{"name": "udata", "value": "{'longtransportid': 1093, 'username': 'syx9220', 'password': 123456}"}], "start": 1660213983785, "stop": 1660213984233, "uuid": "4b264f96-3b12-4466-82c1-3048e17269db", "historyId": "47ea4e34bbf082a7c68fcbe9a27e34b2", "testCaseId": "d71a2910c5a241c986cecb1081c4532c", "fullName": "py_test.TestCase#test_loginError", "labels": [{"name": "suite", "value": "py_test"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "xiaocaodeMac.local"}, {"name": "thread", "value": "5724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "py_test"}]}