{"name": "test_loginError[udata1]", "status": "passed", "parameters": [{"name": "udata", "value": "{'longtransportid': 1093, 'username': 'syx9220', 'password': 12345}"}], "start": 1660213988510, "stop": 1660213988883, "uuid": "34a65c32-4c74-4a7c-99d7-9bd6f967af68", "historyId": "230c2c4b43f310daf6664a452888b54f", "testCaseId": "d71a2910c5a241c986cecb1081c4532c", "fullName": "py_test.TestCase#test_loginError", "labels": [{"name": "suite", "value": "py_test"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "xiaocaodeMac.local"}, {"name": "thread", "value": "5724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "py_test"}]}